// =============================================================================
// FILE: tcu_scoreboard.svh
// =============================================================================
// DESCRIPTION:
//   Temporal Coalescing Unit (TCU) Scoreboard component for UVM verification
//   environment. This scoreboard implements a reference model that mimics the
//   TCU's coalescing behavior and performs functional comparison between
//   expected and actual outputs.
//
// FUNCTIONALITY:
//   - Receives input transactions and coalesces them based on matching criteria
//   - Models timeout-based flushing behavior matching DUT specifications
//   - Generates expected output transactions based on coalescing logic
//   - Performs sanity checks on actual outputs from DUT
//   - Compares expected vs. actual outputs and reports mismatches
//   - Provides comprehensive statistics and test pass/fail reporting
//
// COALESCING CRITERIA:
//   Transactions are coalesced when all of the following match:
//   - Base address (cache-line aligned)
//   - Block ID
//   - Base thread ID (8-thread aligned)
//   - Write enable flag
//   - Load destination register (for reads)
//
// TIMEOUT MECHANISM:
//   - Flushes buffer immediately if no coalescable input arrives in a cycle
//   - Flushes buffer after MAX_COALESCE_INTERVAL cycles of continuous coalescing
//
// =============================================================================

// Macro declarations for multiple analysis import implementations
`uvm_analysis_imp_decl(_in)
`uvm_analysis_imp_decl(_out)

//------------------------------------------------------------------------------
// CLASS: tcu_scoreboard
//------------------------------------------------------------------------------
// UVM scoreboard component that verifies the functional correctness of the
// Temporal Coalescing Unit by implementing a behavioral reference model.
//------------------------------------------------------------------------------
class tcu_scoreboard extends uvm_component;
  `uvm_component_utils(tcu_scoreboard)

  //----------------------------------------------------------------------------
  // Analysis Ports
  //----------------------------------------------------------------------------

  // Analysis import for receiving input transactions from input monitor
  uvm_analysis_imp_in  #(tcu_seq_item, tcu_scoreboard) in_imp;

  // Analysis import for receiving output transactions from output monitor
  uvm_analysis_imp_out #(tcu_out_item, tcu_scoreboard) out_imp;

  //----------------------------------------------------------------------------
  // Virtual Interface
  //----------------------------------------------------------------------------

  // Virtual interface handle for clock-based timeout modeling and synchronization
  virtual tcu_if.monitor_mp vif;

  //----------------------------------------------------------------------------
  // Reference Model Queues
  //----------------------------------------------------------------------------

  // Queue of expected output transactions generated by the reference model
  tcu_out_item expected_q[$];

  // Queue of actual output transactions received from the DUT
  tcu_out_item actual_outputs[$];

  //----------------------------------------------------------------------------
  // Coalescing Buffer State Variables
  //----------------------------------------------------------------------------

  // Indicates if the coalescing buffer currently contains valid data
  bit          buffer_valid;

  // Cache-line aligned base address of transactions in buffer
  bit [63:0]   buffer_base_addr;

  // Block ID of transactions in buffer
  bit [3:0]    buffer_block_id;

  // 8-thread aligned base thread ID of transactions in buffer
  bit [9:0]    buffer_base_tid;

  // Bitmap indicating which threads (0-7) have been coalesced
  bit [7:0]    buffer_tid_bitmap;

  // Write enable flag (1=write, 0=read) for transactions in buffer
  bit          buffer_write_enable;

  // Load destination register for read operations
  bit [6:0]    buffer_ld_dest_reg;

  // Coalesced write data (256 bits = 32 bytes for cache line)
  bit [255:0]  buffer_write_data;

  // Write byte mask (32 bits = 1 bit per byte, 0=valid, 1=masked)
  bit [31:0]   buffer_write_mask;

  // Transaction size encoding (00=1B, 01=2B, 10=4B, 11=8B)
  bit [1:0]    buffer_size;

  //----------------------------------------------------------------------------
  // Timeout Modeling Parameters and Variables
  //----------------------------------------------------------------------------

  // Maximum number of cycles to wait before flushing buffer (matches DUT)
  localparam int MAX_COALESCE_INTERVAL = 8;

  // Counter tracking number of consecutive coalescing cycles
  int unsigned interval_counter;

  // Flag indicating if a coalescable input arrived in current clock cycle
  bit coalescable_input_this_cycle;

  //----------------------------------------------------------------------------
  // Statistics Counters
  //----------------------------------------------------------------------------

  // Total number of input transactions received
  int unsigned num_inputs;

  // Total number of output transactions received
  int unsigned num_outputs;

  // Number of output comparisons that matched expected values
  int unsigned num_matches;

  // Number of output comparisons that did not match expected values
  int unsigned num_mismatches;

  // Number of output sanity checks that passed
  int unsigned num_sanity_passes;

  // Number of output sanity checks that failed
  int unsigned num_sanity_failures;

  //----------------------------------------------------------------------------
  // Cache Configuration Parameters
  //----------------------------------------------------------------------------

  // Cache line size in bytes (32 bytes)
  localparam int CACHE_LINE_SIZE = 32;

  // Number of address bits to mask for cache-line alignment
  localparam int BASE_ADDR_OFFSET = $clog2(CACHE_LINE_SIZE);

  //----------------------------------------------------------------------------
  // FUNCTION: new
  //----------------------------------------------------------------------------
  // Constructor for the tcu_scoreboard component.
  //
  // PARAMETERS:
  //   name   - Instance name of the scoreboard component (default: "tcu_scoreboard")
  //   parent - Handle to the parent component in UVM hierarchy (default: null)
  //----------------------------------------------------------------------------
  function new(string name = "tcu_scoreboard", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: build_phase
  //----------------------------------------------------------------------------
  // UVM build phase for constructing scoreboard sub-components and initializing
  // member variables. Executes during testbench elaboration.
  //
  // OPERATIONS:
  //   - Creates analysis import objects for input and output ports
  //   - Retrieves virtual interface from configuration database
  //   - Initializes coalescing buffer state to empty
  //   - Resets all timeout and statistics counters to zero
  //
  // PARAMETERS:
  //   phase - UVM phase object controlling execution flow
  //
  // FATAL ERROR:
  //   Raises NOVIF fatal error if virtual interface is not found in config_db
  //----------------------------------------------------------------------------
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // Create analysis import instances
    in_imp  = new("in_imp",  this);
    out_imp = new("out_imp", this);

    // Retrieve virtual interface from configuration database
    if (!uvm_config_db#(virtual tcu_if.monitor_mp)::get(this, "", "vif", vif)) begin
      `uvm_fatal("NOVIF", "Virtual interface not set for tcu_scoreboard")
    end

    // Initialize coalescing buffer state
    buffer_valid = 0;
    interval_counter = 0;
    coalescable_input_this_cycle = 0;

    // Initialize statistics counters
    num_inputs = 0;
    num_outputs = 0;
    num_matches = 0;
    num_mismatches = 0;
    num_sanity_passes = 0;
    num_sanity_failures = 0;
  endfunction

  //----------------------------------------------------------------------------
  // TASK: run_phase
  //----------------------------------------------------------------------------
  // UVM run phase that executes concurrently with the testbench simulation.
  // Implements clock-synchronized timeout monitoring for the coalescing buffer.
  //
  // BEHAVIOR:
  //   This task runs continuously in an infinite loop, synchronized to the
  //   positive edge of the clock. It monitors the coalescing buffer state and
  //   implements two flushing mechanisms:
  //
  //   1. IMMEDIATE FLUSH: If buffer is valid but no coalescable input arrived
  //      in the current cycle, flush immediately. This matches DUT behavior
  //      where output_valid = !buffer_can_coalesce.
  //
  //   2. TIMEOUT FLUSH: If inputs continue to coalesce for MAX_COALESCE_INTERVAL
  //      consecutive cycles, flush the buffer to prevent indefinite waiting.
  //
  // PARAMETERS:
  //   phase - UVM phase object controlling execution flow
  //
  // NOTE:
  //   The coalescable_input_this_cycle flag is set by write_in() and cleared
  //   at the end of each clock cycle to detect idle cycles.
  //----------------------------------------------------------------------------
  task run_phase(uvm_phase phase);
    forever begin
      // Wait for positive clock edge to synchronize with DUT
      @(posedge vif.clk);

      // Process buffer timeout logic if buffer contains valid data
      if (buffer_valid) begin
        // IMMEDIATE FLUSH CONDITION:
        // No coalescable input arrived this cycle, output should be generated
        // This matches DUT behavior: output_valid = !buffer_can_coalesce
        if (!coalescable_input_this_cycle) begin
          `uvm_info("SCB", "No coalescable input this cycle, flushing buffer", UVM_HIGH)
          flush_buffer();
          interval_counter = 0;
        end
        else begin
          // Input did arrive and was coalesced, increment timeout counter
          interval_counter++;

          // TIMEOUT FLUSH CONDITION:
          // Maximum coalescing interval reached, force buffer flush
          if (interval_counter >= MAX_COALESCE_INTERVAL) begin
            `uvm_info("SCB", "Timeout reached, flushing buffer", UVM_HIGH)
            flush_buffer();
            interval_counter = 0;
          end
        end
      end

      // Reset the coalescable flag for next clock cycle
      coalescable_input_this_cycle = 0;
    end
  endtask

  //----------------------------------------------------------------------------
  // FUNCTION: write_in
  //----------------------------------------------------------------------------
  // Analysis port write method called by the input monitor when a new input
  // transaction is observed. Implements the coalescing logic of the reference
  // model.
  //
  // COALESCING ALGORITHM:
  //   1. Calculate cache-line aligned base address and thread-group base TID
  //   2. Check if transaction can coalesce with existing buffer based on:
  //      - Matching base address (cache-line aligned)
  //      - Matching block ID
  //      - Matching base TID (8-thread aligned)
  //      - Matching write enable flag
  //      - Matching load destination register (for reads only)
  //   3. Execute one of three actions:
  //      a) If buffer is empty: Initialize new buffer with this transaction
  //      b) If can coalesce: Merge transaction into existing buffer
  //      c) If cannot coalesce: Flush buffer and initialize new buffer
  //
  // PARAMETERS:
  //   tr - Input transaction item received from the input monitor
  //
  // SIDE EFFECTS:
  //   - Updates num_inputs counter
  //   - May flush current buffer and generate expected output
  //   - May initialize or update coalescing buffer state
  //   - Sets coalescable_input_this_cycle flag for timeout logic
  //   - May reset interval_counter
  //----------------------------------------------------------------------------
  function void write_in(tcu_seq_item tr);
    bit [63:0] in_base_addr;
    bit [9:0]  in_base_tid;
    bit        can_coalesce;

    // Increment input transaction counter
    num_inputs++;
    `uvm_info("SCB_IN", $sformatf("Received input #%0d: %s", num_inputs, tr.convert2string()), UVM_MEDIUM)

    // Calculate cache-line aligned base address (clear lower bits)
    in_base_addr = {tr.address[63:BASE_ADDR_OFFSET], {BASE_ADDR_OFFSET{1'b0}}};

    // Calculate 8-thread aligned base TID (clear lower 3 bits)
    in_base_tid = {tr.tid[9:3], 3'b0};

    // Determine if this transaction can coalesce with current buffer
    // All criteria must match for coalescing to occur
    can_coalesce = buffer_valid &&
                   (buffer_base_addr == in_base_addr) &&
                   (buffer_block_id == tr.block_id) &&
                   (buffer_base_tid == in_base_tid) &&
                   (buffer_write_enable == tr.write_enable) &&
                   (buffer_ld_dest_reg == tr.ld_dest_reg || tr.write_enable);

    // CASE 1: Buffer is empty - initialize new buffer
    if (!buffer_valid) begin
      init_buffer(tr, in_base_addr, in_base_tid);
      interval_counter = 0;  // Reset timeout counter for new buffer
      coalescable_input_this_cycle = 1;  // New buffer started
      `uvm_info("SCB_IN", "Started new coalescing buffer", UVM_HIGH)
    end
    // CASE 2: Transaction can coalesce - merge into existing buffer
    else if (can_coalesce) begin
      merge_into_buffer(tr);
      coalescable_input_this_cycle = 1;  // Input coalesced
      // Note: DUT does NOT reset counter on coalesce, it keeps counting
      `uvm_info("SCB_IN", "Merged into existing buffer", UVM_HIGH)
    end
    // CASE 3: Transaction cannot coalesce - flush and start new buffer
    else begin
      flush_buffer();
      init_buffer(tr, in_base_addr, in_base_tid);
      interval_counter = 0;  // Reset timeout counter for new buffer
      coalescable_input_this_cycle = 1;  // New buffer started after flush
      `uvm_info("SCB_IN", "Flushed buffer, started new", UVM_HIGH)
    end
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: write_out
  //----------------------------------------------------------------------------
  // Analysis port write method called by the output monitor when a new output
  // transaction is observed from the DUT. Stores actual outputs and performs
  // sanity checks.
  //
  // OPERATIONS:
  //   - Increments output transaction counter
  //   - Logs received output transaction
  //   - Adds transaction to actual outputs queue for later comparison
  //   - Performs sanity checks on the output data
  //
  // PARAMETERS:
  //   tr - Output transaction item received from the output monitor
  //
  // SIDE EFFECTS:
  //   - Updates num_outputs counter
  //   - Appends transaction to actual_outputs queue
  //   - May update sanity check counters
  //----------------------------------------------------------------------------
  function void write_out(tcu_out_item tr);
    num_outputs++;
    `uvm_info("SCB_OUT", $sformatf("Received output #%0d: %s", num_outputs, tr.convert2string()), UVM_MEDIUM)
    actual_outputs.push_back(tr);
    check_output_sanity(tr);
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: check_output_sanity
  //----------------------------------------------------------------------------
  // Performs basic sanity checks on output transactions to detect obvious
  // protocol violations or malformed data before functional comparison.
  //
  // SANITY CHECKS PERFORMED:
  //   1. TID Bitmap Non-Empty: Ensures at least one thread is coalesced
  //      (tid_bitmap != 0)
  //
  //   2. Cache-Line Alignment: Verifies address is aligned to cache line
  //      boundary (address[4:0] == 0 for 32-byte cache lines)
  //
  //   3. Write Mask Validity: Warns if write operation has all bytes masked
  //      (write_enable && write_mask == all 1s)
  //
  // PARAMETERS:
  //   tr - Output transaction to check
  //
  // SIDE EFFECTS:
  //   - Increments num_sanity_passes if all checks pass
  //   - Increments num_sanity_failures and reports error if check fails
  //   - Early return on first failure to avoid multiple errors per transaction
  //----------------------------------------------------------------------------
  function void check_output_sanity(tcu_out_item tr);
    // Check 1: TID bitmap must have at least one valid thread
    if (tr.tid_bitmap == 0) begin
      `uvm_error("SCB", "Output has empty tid_bitmap")
      num_sanity_failures++;
      return;
    end

    // Check 2: Address must be cache-line aligned (lower 5 bits = 0)
    if (tr.address[4:0] != 0) begin
      `uvm_error("SCB", $sformatf("Output address 0x%h is not cache-line aligned", tr.address))
      num_sanity_failures++;
      return;
    end

    // Check 3: Write with all bytes masked is unusual (warning only)
    if (tr.write_enable && tr.write_mask == '1) begin
      `uvm_warning("SCB", "Write output has all bytes masked")
    end

    // All sanity checks passed
    num_sanity_passes++;
    `uvm_info("SCB", "Output passed sanity checks", UVM_HIGH)
  endfunction

  //----------------------------------------------------------------------------
  // Helper Functions for Coalescing Buffer Management
  //----------------------------------------------------------------------------

  //----------------------------------------------------------------------------
  // FUNCTION: init_buffer
  //----------------------------------------------------------------------------
  // Initializes the coalescing buffer with the first transaction of a new
  // coalescing group. Sets all buffer state variables and marks the buffer
  // as valid.
  //
  // INITIALIZATION OPERATIONS:
  //   - Marks buffer as valid
  //   - Sets base address and base TID (both pre-aligned by caller)
  //   - Copies block ID, write enable, destination register, and size
  //   - Initializes write mask to all 1s (all bytes masked initially)
  //   - Initializes write data to all 0s
  //   - Sets TID bitmap bit for this transaction's thread offset
  //   - For write operations: Applies write data to buffer at proper offset
  //
  // PARAMETERS:
  //   tr        - Input transaction to initialize buffer with
  //   base_addr - Cache-line aligned base address (pre-calculated)
  //   base_tid  - 8-thread aligned base TID (pre-calculated)
  //
  // SIDE EFFECTS:
  //   - Sets buffer_valid to 1
  //   - Updates all buffer_* state variables
  //   - For writes: Updates buffer_write_data and buffer_write_mask
  //----------------------------------------------------------------------------
  function void init_buffer(tcu_seq_item tr, bit [63:0] base_addr, bit [9:0] base_tid);
    bit [4:0] addr_offset;
    bit [2:0] tid_offset;

    // Mark buffer as containing valid coalescing data
    buffer_valid        = 1;
    buffer_base_addr    = base_addr;
    buffer_block_id     = tr.block_id;
    buffer_base_tid     = base_tid;
    buffer_write_enable = tr.write_enable;
    buffer_ld_dest_reg  = tr.ld_dest_reg;
    buffer_size         = tr.size;

    // Initialize write mask to all 1s (masked) and data to 0s
    buffer_write_mask   = '1;
    buffer_write_data   = '0;

    // Set TID bitmap bit for this thread (offset within 8-thread group)
    tid_offset = tr.tid[2:0];
    buffer_tid_bitmap = (1 << tid_offset);

    // For write operations, apply the write data to buffer
    if (tr.write_enable) begin
      addr_offset = tr.address[4:0];
      apply_write_to_buffer(tr, addr_offset);
    end
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: merge_into_buffer
  //----------------------------------------------------------------------------
  // Merges a coalescable transaction into the existing coalescing buffer.
  // Updates the TID bitmap and, for write operations, merges the write data.
  //
  // MERGE OPERATIONS:
  //   - Sets the TID bitmap bit for this transaction's thread
  //   - For write operations: Merges write data into buffer at proper offset
  //
  // PARAMETERS:
  //   tr - Input transaction to merge into existing buffer
  //
  // PRECONDITIONS:
  //   - buffer_valid must be 1
  //   - Transaction must have passed coalescing criteria check
  //
  // SIDE EFFECTS:
  //   - Updates buffer_tid_bitmap with new thread bit
  //   - For writes: Updates buffer_write_data and buffer_write_mask
  //
  // NOTE:
  //   This function assumes the caller has already verified that coalescing
  //   is allowed (matching base_addr, block_id, base_tid, write_enable, etc.)
  //----------------------------------------------------------------------------
  function void merge_into_buffer(tcu_seq_item tr);
    bit [4:0] addr_offset;
    bit [2:0] tid_offset;

    // Add this thread to the TID bitmap (OR operation sets the bit)
    tid_offset = tr.tid[2:0];
    buffer_tid_bitmap |= (1 << tid_offset);

    // For write operations, merge the write data into buffer
    if (tr.write_enable) begin
      addr_offset = tr.address[4:0];
      apply_write_to_buffer(tr, addr_offset);
    end
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: apply_write_to_buffer
  //----------------------------------------------------------------------------
  // Applies write data from a transaction to the coalescing buffer at the
  // specified address offset. Handles byte-level write masking and merging
  // of multiple writes within the same cache line.
  //
  // WRITE MERGING ALGORITHM:
  //   1. Decode transaction size to actual byte count (1, 2, 4, or 8 bytes)
  //   2. For each byte in the write:
  //      - Check if byte is enabled (write_mask[i] == 0)
  //      - If enabled: Copy data byte to buffer at (addr_offset + i)
  //      - Update buffer's write mask to mark byte as valid (0 = valid)
  //
  // SIZE ENCODING:
  //   2'b00 = 1 byte
  //   2'b01 = 2 bytes
  //   2'b10 = 4 bytes
  //   2'b11 = 8 bytes
  //
  // MASK CONVENTION:
  //   0 = byte is valid/enabled (should be written)
  //   1 = byte is masked/disabled (should not be written)
  //
  // PARAMETERS:
  //   tr          - Input transaction containing write data and mask
  //   addr_offset - Byte offset within cache line (0-31)
  //
  // SIDE EFFECTS:
  //   - Updates buffer_write_data for enabled bytes
  //   - Updates buffer_write_mask to mark bytes as valid
  //
  // NOTE:
  //   Loop is bounded to 8 bytes max to match transaction data width
  //----------------------------------------------------------------------------
  function void apply_write_to_buffer(tcu_seq_item tr, bit [4:0] addr_offset);
    int actual_size;

    // Decode size encoding to actual byte count
    case (tr.size)
      2'b00: actual_size = 1;  // Byte
      2'b01: actual_size = 2;  // Half-word
      2'b10: actual_size = 4;  // Word
      2'b11: actual_size = 8;  // Double-word
    endcase

    // Iterate over each byte in the write transaction
    for (int i = 0; i < actual_size && i < 8; i++) begin
      // Only apply bytes that are not masked (mask bit = 0 means valid)
      if (!tr.write_mask[i]) begin
        // Copy data byte to buffer at the calculated offset
        buffer_write_data[(addr_offset + i) * 8 +: 8] = tr.write_data[i * 8 +: 8];
        // Mark this byte as valid in buffer's write mask
        buffer_write_mask[addr_offset + i] = 0;
      end
    end
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: flush_buffer
  //----------------------------------------------------------------------------
  // Flushes the current coalescing buffer by creating an expected output
  // transaction and adding it to the expected outputs queue. This represents
  // the reference model's prediction of what the DUT should output.
  //
  // FLUSH OPERATIONS:
  //   1. Check if buffer is valid (early return if empty)
  //   2. Create new expected output transaction
  //   3. Copy all buffer state to expected output:
  //      - Block ID
  //      - Base TID and TID bitmap
  //      - Address (cache-line aligned)
  //      - Write enable flag
  //      - Write data and write mask (for writes)
  //      - Size and destination register
  //   4. Add expected output to queue for later comparison
  //   5. Mark buffer as invalid (ready for next coalescing group)
  //
  // PARAMETERS:
  //   None
  //
  // SIDE EFFECTS:
  //   - Creates new tcu_out_item and adds to expected_q
  //   - Sets buffer_valid to 0
  //   - Logs expected output at UVM_HIGH verbosity
  //
  // USAGE:
  //   Called when:
  //   - No coalescable input arrives (immediate flush)
  //   - Timeout counter reaches MAX_COALESCE_INTERVAL
  //   - New non-coalescable transaction arrives
  //   - End of simulation (report_phase)
  //----------------------------------------------------------------------------
  function void flush_buffer();
    tcu_out_item exp;

    // Early return if buffer is already empty
    if (!buffer_valid) return;

    // Create expected output transaction using UVM factory
    exp = tcu_out_item::type_id::create("exp");

    // Copy all buffer state to expected output
    exp.block_id     = buffer_block_id;
    exp.base_tid     = buffer_base_tid;
    exp.tid_bitmap   = buffer_tid_bitmap;
    exp.write_enable = buffer_write_enable;
    exp.write_data   = buffer_write_data;
    exp.write_mask   = buffer_write_mask;
    exp.address      = buffer_base_addr;
    exp.size         = buffer_size;
    exp.ld_dest_reg  = buffer_ld_dest_reg;

    // Add expected output to queue for comparison with actual DUT outputs
    expected_q.push_back(exp);

    // Mark buffer as invalid/empty
    buffer_valid = 0;

    `uvm_info("SCB", $sformatf("Pushed expected output: %s", exp.convert2string()), UVM_HIGH)
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: compare_outputs
  //----------------------------------------------------------------------------
  // Performs field-by-field comparison between an expected output transaction
  // (from reference model) and an actual output transaction (from DUT).
  //
  // FIELDS COMPARED:
  //   - block_id:     Block identifier must match
  //   - base_tid:     Base thread ID (8-thread aligned) must match
  //   - tid_bitmap:   Thread coalescing bitmap must match
  //   - address:      Cache-line aligned address must match
  //   - write_enable: Read/write operation type must match
  //
  // NOTE: Write data and mask are not compared here to focus on control fields.
  //       These could be added if needed for write verification.
  //
  // PARAMETERS:
  //   exp - Expected output transaction from reference model
  //   act - Actual output transaction from DUT
  //
  // RETURNS:
  //   1 if all compared fields match, 0 if any mismatch found
  //
  // SIDE EFFECTS:
  //   - Logs mismatch details at UVM_LOW verbosity for each failed field
  //----------------------------------------------------------------------------
  function bit compare_outputs(tcu_out_item exp, tcu_out_item act);
    bit match = 1;

    // Compare block ID
    if (exp.block_id != act.block_id) begin
      `uvm_info("SCB", $sformatf("block_id mismatch: exp=%0h act=%0h", exp.block_id, act.block_id), UVM_LOW)
      match = 0;
    end

    // Compare base thread ID
    if (exp.base_tid != act.base_tid) begin
      `uvm_info("SCB", $sformatf("base_tid mismatch: exp=%0h act=%0h", exp.base_tid, act.base_tid), UVM_LOW)
      match = 0;
    end

    // Compare thread bitmap
    if (exp.tid_bitmap != act.tid_bitmap) begin
      `uvm_info("SCB", $sformatf("tid_bitmap mismatch: exp=%0h act=%0h", exp.tid_bitmap, act.tid_bitmap), UVM_LOW)
      match = 0;
    end

    // Compare address
    if (exp.address != act.address) begin
      `uvm_info("SCB", $sformatf("address mismatch: exp=%0h act=%0h", exp.address, act.address), UVM_LOW)
      match = 0;
    end

    // Compare write enable flag
    if (exp.write_enable != act.write_enable) begin
      `uvm_info("SCB", $sformatf("write_enable mismatch: exp=%0h act=%0h", exp.write_enable, act.write_enable), UVM_LOW)
      match = 0;
    end

    return match;
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: compare_expected_to_actual
  //----------------------------------------------------------------------------
  // Performs comprehensive comparison between all expected outputs (from
  // reference model) and actual outputs (from DUT). Handles three scenarios:
  // matching pairs, missing outputs, and unexpected extra outputs.
  //
  // COMPARISON ALGORITHM:
  //   1. Determine minimum count between expected and actual queues
  //   2. Compare pairs of transactions up to minimum count:
  //      - Increment num_matches on success
  //      - Increment num_mismatches and log error on failure
  //   3. Check for extra expected outputs (DUT produced fewer outputs):
  //      - Each missing output counts as a mismatch
  //      - Reports total number of missing outputs
  //   4. Check for extra actual outputs (DUT produced more outputs):
  //      - Each extra output counts as a mismatch
  //      - Reports total number of unexpected outputs
  //
  // PARAMETERS:
  //   None (operates on member variables expected_q and actual_outputs)
  //
  // SIDE EFFECTS:
  //   - Updates num_matches counter
  //   - Updates num_mismatches counter
  //   - Logs comparison results and errors
  //
  // USAGE:
  //   Called during report_phase after all transactions have been collected
  //   and the final buffer has been flushed.
  //----------------------------------------------------------------------------
  function void compare_expected_to_actual();
    int min_count;
    int extra_expected;
    int extra_actual;

    // Determine how many pairs we can compare (minimum of both queue sizes)
    min_count = (expected_q.size() < actual_outputs.size()) ? expected_q.size() : actual_outputs.size();

    // Compare all transaction pairs
    for (int i = 0; i < min_count; i++) begin
      if (compare_outputs(expected_q[i], actual_outputs[i])) begin
        num_matches++;
        `uvm_info("SCB", $sformatf("Output match #%0d", i + 1), UVM_HIGH)
      end
      else begin
        num_mismatches++;
        `uvm_error("SCB", $sformatf("Output mismatch #%0d exp=%s act=%s",
                                    i + 1, expected_q[i].convert2string(), actual_outputs[i].convert2string()))
      end
    end

    // Calculate and report extra expected outputs (missing from DUT)
    extra_expected = expected_q.size() - min_count;
    extra_actual = actual_outputs.size() - min_count;

    if (extra_expected > 0) begin
      num_mismatches += extra_expected;
      `uvm_error("SCB", $sformatf("Missing %0d actual outputs; expected queue still has items", extra_expected))
    end

    // Calculate and report extra actual outputs (unexpected from DUT)
    if (extra_actual > 0) begin
      num_mismatches += extra_actual;
      `uvm_error("SCB", $sformatf("Received %0d unexpected extra outputs", extra_actual))
    end
  endfunction

  //----------------------------------------------------------------------------
  // FUNCTION: report_phase
  //----------------------------------------------------------------------------
  // UVM report phase executed at end of simulation. Performs final verification
  // checks, computes statistics, and generates comprehensive test report with
  // pass/fail determination.
  //
  // REPORT PHASE OPERATIONS:
  //   1. Flush any remaining buffered transaction
  //   2. Perform complete expected vs. actual comparison
  //   3. Calculate coalescing efficiency metrics:
  //      - Count total coalesced threads across all outputs
  //      - Compute coalescing ratio (threads per output)
  //   4. Display comprehensive summary including:
  //      - Transaction counts (inputs/outputs)
  //      - Coalescing efficiency ratio
  //      - Sanity check results (passes/failures)
  //      - Functional comparison results (matches/mismatches)
  //   5. Determine test pass/fail status with priority:
  //      a) FAIL if any sanity checks failed (basic protocol violations)
  //      b) FAIL if any functional mismatches found
  //      c) FAIL if no outputs received despite having inputs
  //      d) PASS if all checks passed
  //
  // PARAMETERS:
  //   phase - UVM phase object controlling execution flow
  //
  // SIDE EFFECTS:
  //   - Flushes remaining buffer
  //   - Performs final comparison
  //   - Prints detailed summary report
  //   - Reports final test status (PASS/FAIL)
  //
  // TEST FAILURE HIERARCHY:
  //   Sanity failures take precedence over functional mismatches, as they
  //   indicate fundamental protocol violations that invalidate further checks.
  //----------------------------------------------------------------------------
  function void report_phase(uvm_phase phase);
    int total_coalesced_tids;

    super.report_phase(phase);

    // Flush any remaining buffered transaction
    flush_buffer();

    // Perform final comparison of all expected vs. actual outputs
    compare_expected_to_actual();

    // Calculate total coalesced threads for efficiency metrics
    total_coalesced_tids = 0;
    foreach (actual_outputs[i]) begin
      for (int b = 0; b < 8; b++) begin
        if (actual_outputs[i].tid_bitmap[b]) total_coalesced_tids++;
      end
    end

    // Display comprehensive scoreboard summary
    `uvm_info("SCB", "========== SCOREBOARD SUMMARY ==========", UVM_LOW)
    `uvm_info("SCB", $sformatf("  Total Inputs:          %0d", num_inputs), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Total Outputs:         %0d", num_outputs), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Coalescing Ratio:      %.2f:1",
                               num_outputs > 0 ? real'(total_coalesced_tids)/real'(num_outputs) : 0), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Sanity Checks Passed:  %0d", num_sanity_passes), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Sanity Checks Failed:  %0d", num_sanity_failures), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Functional Matches:    %0d", num_matches), UVM_LOW)
    `uvm_info("SCB", $sformatf("  Functional Mismatches: %0d", num_mismatches), UVM_LOW)
    `uvm_info("SCB", "=========================================", UVM_LOW)

    // Determine test pass/fail status (priority order matters)
    if (num_sanity_failures > 0) begin
      `uvm_error("SCB", $sformatf("TEST FAILED: %0d sanity check failures", num_sanity_failures))
    end
    else if (num_mismatches > 0) begin
      `uvm_error("SCB", $sformatf("TEST FAILED: %0d functional mismatches", num_mismatches))
    end
    else if (num_outputs == 0 && num_inputs > 0) begin
      `uvm_error("SCB", "TEST FAILED: No outputs received despite inputs!")
    end
    else begin
      `uvm_info("SCB", "TEST PASSED - All sanity checks passed", UVM_LOW)
    end
  endfunction

endclass
