+incdir+${DICE_HOME}/rtl
+incdir+${DICE_HOME}/hw/rtl
${DICE_HOME}/rtl/dice_config.vh
${DICE_HOME}/rtl/dice_define.vh
${DICE_HOME}/rtl/dice_pkg.sv
${DICE_HOME}/rtl/dice_frontend_pkg.sv
${DICE_HOME}/hw/rtl/VX_define.vh
${DICE_HOME}/hw/rtl/VX_gpu_pkg.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/decode.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/meta_fetch.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/bitstream_fetch_load.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/branch_handler.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/valid_check.sv
${DICE_HOME}/rtl/cgra_core/fetch_stage/fdr_top.sv
${DICE_HOME}/tb/cgra_core/FDR_stage/fdr_top/fdr_top_tb.sv
