`timescale 1ns/1ps
/*
 * AUTO-GENERATED by dice_alu_generator.py — DO NOT EDIT.
 * name: dice_alu
 * inputs: 4 widths: [32, 32, 32, 1]
 * outputs: 2 widths: [32, 1]
 */

package dice_alu_pkg;
  localparam int unsigned OPCODE_ADD_U32 = 32'h0;
  localparam int unsigned OPCODE_SUB_U32 = 32'h1;
  localparam int unsigned OPCODE_MUL_LO_U32 = 32'h2;
  localparam int unsigned OPCODE_MAD_U32 = 32'h3;
  localparam int unsigned OPCODE_DIV_U32 = 32'h4;
  localparam int unsigned OPCODE_REM_U32 = 32'h5;
  localparam int unsigned OPCODE_ADD_S32 = 32'hA;
  localparam int unsigned OPCODE_SUB_S32 = 32'hB;
  localparam int unsigned OPCODE_MUL_LO_S32 = 32'hC;
  localparam int unsigned OPCODE_DIV_S32 = 32'hD;
  localparam int unsigned OPCODE_REM_S32 = 32'hE;
  localparam int unsigned OPCODE_AND_B32 = 32'h14;
  localparam int unsigned OPCODE_OR_B32 = 32'h15;
  localparam int unsigned OPCODE_XOR_B32 = 32'h16;
  localparam int unsigned OPCODE_NOT_B32 = 32'h17;
  localparam int unsigned OPCODE_SHL_B32 = 32'h1E;
  localparam int unsigned OPCODE_SHR_U32 = 32'h1F;
  localparam int unsigned OPCODE_SHR_S32 = 32'h20;
  localparam int unsigned OPCODE_MIN_U32 = 32'h28;
  localparam int unsigned OPCODE_MAX_U32 = 32'h29;
  localparam int unsigned OPCODE_MIN_S32 = 32'h2A;
  localparam int unsigned OPCODE_MAX_S32 = 32'h2B;
  localparam int unsigned OPCODE_ADD_F32 = 32'hC8;
  localparam int unsigned OPCODE_SUB_F32 = 32'hC9;
  localparam int unsigned OPCODE_MUL_F32 = 32'hCA;
  localparam int unsigned OPCODE_DIV_F32 = 32'hCB;
  localparam int unsigned OPCODE_MAD_F32 = 32'hCC;
  localparam int unsigned OPCODE_MIN_F32 = 32'hCD;
  localparam int unsigned OPCODE_MAX_F32 = 32'hCE;
  localparam int unsigned OPCODE_SET_EQ_U32 = 32'h32;
  localparam int unsigned OPCODE_SET_NE_U32 = 32'h33;
  localparam int unsigned OPCODE_SET_LT_U32 = 32'h34;
  localparam int unsigned OPCODE_SET_LE_U32 = 32'h35;
  localparam int unsigned OPCODE_SET_GT_U32 = 32'h36;
  localparam int unsigned OPCODE_SET_GE_U32 = 32'h37;
  localparam int unsigned OPCODE_SET_LT_S32 = 32'h38;
  localparam int unsigned OPCODE_SET_GT_S32 = 32'h39;
  localparam int unsigned OPCODE_SEL = 32'h64;

  function automatic int op_latency(input int unsigned op);
    case (op)
      OPCODE_ADD_U32: op_latency = 0;
      OPCODE_SUB_U32: op_latency = 0;
      OPCODE_MUL_LO_U32: op_latency = 0;
      OPCODE_MAD_U32: op_latency = 1;
      OPCODE_DIV_U32: op_latency = 2;
      OPCODE_REM_U32: op_latency = 2;
      OPCODE_ADD_S32: op_latency = 0;
      OPCODE_SUB_S32: op_latency = 0;
      OPCODE_MUL_LO_S32: op_latency = 0;
      OPCODE_DIV_S32: op_latency = 0;
      OPCODE_REM_S32: op_latency = 0;
      OPCODE_AND_B32: op_latency = 0;
      OPCODE_OR_B32: op_latency = 0;
      OPCODE_XOR_B32: op_latency = 0;
      OPCODE_NOT_B32: op_latency = 0;
      OPCODE_SHL_B32: op_latency = 0;
      OPCODE_SHR_U32: op_latency = 0;
      OPCODE_SHR_S32: op_latency = 0;
      OPCODE_MIN_U32: op_latency = 0;
      OPCODE_MAX_U32: op_latency = 0;
      OPCODE_MIN_S32: op_latency = 0;
      OPCODE_MAX_S32: op_latency = 0;
      OPCODE_ADD_F32: op_latency = 1;
      OPCODE_SUB_F32: op_latency = 1;
      OPCODE_MUL_F32: op_latency = 1;
      OPCODE_DIV_F32: op_latency = 2;
      OPCODE_MAD_F32: op_latency = 2;
      OPCODE_MIN_F32: op_latency = 1;
      OPCODE_MAX_F32: op_latency = 1;
      OPCODE_SET_EQ_U32: op_latency = 0;
      OPCODE_SET_NE_U32: op_latency = 0;
      OPCODE_SET_LT_U32: op_latency = 0;
      OPCODE_SET_LE_U32: op_latency = 0;
      OPCODE_SET_GT_U32: op_latency = 0;
      OPCODE_SET_GE_U32: op_latency = 0;
      OPCODE_SET_LT_S32: op_latency = 0;
      OPCODE_SET_GT_S32: op_latency = 0;
      OPCODE_SEL: op_latency = 0;
      default: op_latency = 0;
    endcase
  endfunction

endpackage
